### ISSUE TITLE
PhET-iO Fuzz Test Error

### ISSUE THREAD

**Issue by zepumph** [phetsims/balloons-and-static-electricity#276]
```
balloons-and-static-electricity
Uncaught TypeError: contentVBox.setAriaLabelledByElement is not a function
TypeError: contentVBox.setAriaLabelledByElement is not a function
    at new BASEKeyboardHelpContent (http://localhost/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BASEKeyboardHelpContent.js?bust=1497642474537:127:17)
    at http://localhost/balloons-and-static-electricity/js/balloons-and-static-electricity-main.js?bust=1497642474537:38:25
    at window.phetLaunchSimulation (http://localhost/joist/js/SimLauncher.js?bust=1497642474537:50:11)
    at doneLoadingImages (http://localhost/joist/js/SimLauncher.js?bust=1497642474537:64:18)
    at Object.launch (http://localhost/joist/js/SimLauncher.js?bust=1497642474537:118:9)
    at http://localhost/balloons-and-static-electricity/js/balloons-and-static-electricity-main.js?bust=1497642474537:24:15
    at Object.execCb (http://localhost/sherpa/lib/require-2.1.11.js:1650:25)
    at Module.check (http://localhost/sherpa/lib/require-2.1.11.js:866:35)
    at Module. (http://localhost/sherpa/lib/require-2.1.11.js:1113:20)
    at http://localhost/sherpa/lib/require-2.1.11.js:132:17

**Comment by jessegreenberg** [comment]
Hmm, I can't find setAriaLabelledByElement in BASE.  Is this in a branch?  Were new SHAs of BASE built against old Scenery SHAs?

**Comment by zepumph** [comment]
I was in the wrong branch, sorry for the trouble.
