### ISSUE TITLE
CT api mismatches present

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balloons-and-static-electricity#445]
```
balloons-and-static-electricity : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: api mismatches present:

balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.inputListener.firedEmitter:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.inputListener.pressAction:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.inputListener.releaseAction:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.opacityProperty:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.pickableProperty:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.visibleProperty:  5. When the sim is finished starting up, all schema entries must be registered.
Error: Assertion failed: api mismatches present:

balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.inputListener.firedEmitter:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.inputListener.pressAction:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.inputListener.releaseAction:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.opacityProperty:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.pickableProperty:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.visibleProperty:  5. When the sim is finished starting up, all schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1558639857450/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertOutIfErrorsPresent (https://bayes.colorado.edu/continuous-testing/snapshot-1558639857450/tandem/js/phetioAPIValidation.js?bust=1558643104428:235:9)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1558639857450/tandem/js/phetioAPIValidation.js?bust=1558643104428:147:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1558639857450/phet-io/js/phetioEngine.js?bust=1558643104428:125:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1558639857450/axon/js/TinyEmitter.js?bust=1558643104428:58:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1558639857450/axon/js/Emitter.js?bust=1558643104428:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1558639857450/axon/js/Action.js?bust=1558643104428:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1558639857450/axon/js/Emitter.js?bust=1558643104428:61:20)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1558639857450/joist/js/Sim.js?bust=1558643104428:847:50
id: Bayes Chrome
Approximately 5/23/2019, 1:30:57 PM
balloons-and-static-electricity : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: api mismatches present:

balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.inputListener.firedEmitter:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.inputListener.pressAction:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.inputListener.releaseAction:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.opacityProperty:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.pickableProperty:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.visibleProperty:  5. When the sim is finished starting up, all schema entries must be registered.
Error: Assertion failed: api mismatches present:

balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.inputListener.firedEmitter:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.inputListener.pressAction:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.inputListener.releaseAction:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.opacityProperty:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.pickableProperty:  5. When the sim is finished starting up, all schema entries must be registered.,
balloonsAndStaticElectricity.navigationBar.phetButton.phetMenu.fullScreenMenuItem.visibleProperty:  5. When the sim is finished starting up, all schema entries must be registered.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1558639857450/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertOutIfErrorsPresent (https://bayes.colorado.edu/continuous-testing/snapshot-1558639857450/tandem/js/phetioAPIValidation.js?bust=1558643104428:235:9)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1558639857450/tandem/js/phetioAPIValidation.js?bust=1558643104428:147:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1558639857450/phet-io/js/phetioEngine.js?bust=1558643104428:125:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1558639857450/axon/js/TinyEmitter.js?bust=1558643104428:58:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1558639857450/axon/js/Emitter.js?bust=1558643104428:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1558639857450/axon/js/Action.js?bust=1558643104428:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1558639857450/axon/js/Emitter.js?bust=1558643104428:61:20)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1558639857450/joist/js/Sim.js?bust=1558643104428:847:50
id: Bayes Chrome
Approximately 5/23/2019, 1:30:57 PM
```

**Comment by zepumph** [comment]
Yes thanks. That should be fixed next round from commits I forgot to push in https://github.com/phetsims/joist/issues/558. If not, it will be sorted out over there.
