### ISSUE TITLE
CT: induced charge did not change since last description

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balloons-and-static-electricity#459]
This is occurring intermittently in CT, and appears to be related to a11y.

```
balloons-and-static-electricity : accessibility-fuzz : require.js : run
Query: brand=phet&ea&fuzz&a11y&memoryLimit=1000
Uncaught Error: Assertion failed: induced charge did not change since last description
Error: Assertion failed: induced charge did not change since last description
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1572488466197/assert/js/assert.js?bust=1572495537212:22:13)
    at BalloonChargeDescriber.getInducedChargeChangeDescription (https://bayes.colorado.edu/continuous-testing/snapshot-1572488466197/balloons-and-static-electricity/js/balloons-and-static-electricity/view/describers/BalloonChargeDescriber.js?bust=1572495537292:266:17)
    at BalloonDescriber.step (https://bayes.colorado.edu/continuous-testing/snapshot-1572488466197/balloons-and-static-electricity/js/balloons-and-static-electricity/view/describers/BalloonDescriber.js?bust=1572495537292:794:50)
    at BalloonNode.step (https://bayes.colorado.edu/continuous-testing/snapshot-1572488466197/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BalloonNode.js?bust=1572495537292:351:22)
    at BASEView.step (https://bayes.colorado.edu/continuous-testing/snapshot-1572488466197/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BASEView.js?bust=1572495537292:198:30)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1572488466197/joist/js/Sim.js?bust=1572495537292:239:21
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1572488466197/axon/js/Action.js?bust=1572495537292:230:20)
    at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1572488466197/joist/js/Sim.js?bust=1572495537292:971:33)
    at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1572488466197/joist/js/Sim.js?bust=1572495537292:952:14)
    at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/snapshot-1572488466197/joist/js/Sim.js?bust=1572495537292:935:14)
id: Bayes Chrome
Approximately 10/30/2019, 8:21:06 PM
```

**Comment by jessegreenberg** [comment]
Thanks, Ill take a look. RUnning ?fuzzBoard for 120 seconds isn't showing anything yet, ill keep looking.

**Comment by jessegreenberg** [comment]
It has only shown up twice in the last 19 CT iterations so fuzz may not be a good way to find this.

**Comment by pixelzoom** [comment]
Note that the query parameters in the CT test were `?brand=phet&ea&fuzz&a11y&memoryLimit=1000`, not `?fuzzBoard`.

**Comment by jessegreenberg** [comment]
Oh thanks! I assumed accessibility-fuzz meant ?fuzzBoard

**Comment by jessegreenberg** [comment]
With `?fuzz` for about 20 minutes I haven't seen this yet. Inspecting the code I am not seeing why this is happening yet.

**Comment by pixelzoom** [comment]
Have you tried `?brand=phet&ea&fuzz&a11y&memoryLimit=1000`?  Is the `ally` query parameter significant?

**Comment by jessegreenberg** [comment]
`a11y` query param enables accessibility but accessibility is enabled by default for this sim so the query parameter shouldn't be required to hit this.

**Comment by pixelzoom** [comment]
This is a "this never should have occurred" type of assertion.  Consider adding one or more additional assertion upstream to provide more information, and wait for CT to hit it again.

**Comment by jessegreenberg** [comment]
Sounds great, I added assertions, and also some other debugging output to the original assertion message if my new upstream assertions aren't hit.

**Comment by pixelzoom** [comment]
Looks like your revised assertion failed over the weekend:

```
balloons-and-static-electricity : phet-io-tests : assert
9 out of 9 tests passed. 0 failed.

Approximately 11/3/2019, 4:35:22 AM
balloons-and-static-electricity : phet-io-tests : no-assert
9 out of 9 tests passed. 0 failed.

Approximately 11/3/2019, 4:35:22 AM
balloons-and-static-electricity : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: induced charge did not change since last description, debugging info: forceMagnitude: 2.8732065107164666, previousForceMagnitude: 2.8732065107164666, greenBalloonVisible: true, yellowBalloonInducingCharge: true, greenBalloonInducingCharge: false, yellowBalloonTouchingWall: false, greenBalloonTouchingWall: false, wallVisible: true
Error: Assertion failed: induced charge did not change since last description, debugging info: forceMagnitude: 2.8732065107164666, previousForceMagnitude: 2.8732065107164666, greenBalloonVisible: true, yellowBalloonInducingCharge: true, greenBalloonInducingCharge: false, yellowBalloonTouchingWall: false, greenBalloonTouchingWall: false, wallVisible: true
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1572780922258/assert/js/assert.js?bust=1572788387406:22:13)
    at BalloonChargeDescriber.getInducedChargeChangeDescription (https://bayes.colorado.edu/continuous-testing/snapshot-1572780922258/balloons-and-static-electricity/js/balloons-and-static-electricity/view/describers/BalloonChargeDescriber.js?bust=1572788387491:267:17)
    at BalloonDescriber.step (https://bayes.colorado.edu/continuous-testing/snapshot-1572780922258/balloons-and-static-electricity/js/balloons-and-static-electricity/view/describers/BalloonDescriber.js?bust=1572788387491:796:50)
    at BalloonNode.step (https://bayes.colorado.edu/continuous-testing/snapshot-1572780922258/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BalloonNode.js?bust=1572788387491:351:22)
    at BASEView.step (https://bayes.colorado.edu/continuous-testing/snapshot-1572780922258/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BASEView.js?bust=1572788387491:198:30)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1572780922258/joist/js/Sim.js?bust=1572788387491:239:21
    at Action.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1572780922258/axon/js/Action.js?bust=1572788387491:230:20)
    at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1572780922258/joist/js/Sim.js?bust=1572788387491:971:33)
    at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/snapshot-1572780922258/joist/js/Sim.js?bust=1572788387491:952:14)
    at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/snapshot-1572780922258/joist/js/Sim.js?bust=1572788387491:935:14)
id: Bayes Chrome
Approximately 11/3/2019, 4:35:22 AM
```

**Comment by KatieWoe** [comment]
Noting that this still seems to show up from time to time:
```
balloons-and-static-electricity : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/balloons-and-static-electricity/balloons-and-static-electricity_en.html?continuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1619678755408%22%2C%22timestamp%22%3A1619697149263%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught Error: Assertion failed: induced charge did not change since last description, debugging info: forceMagnitude: 2.92421007109607, previousForceMagnitude: 2.92421007109607, greenBalloonVisible: false, yellowBalloonInducingCharge: true, greenBalloonInducingCharge: false, yellowBalloonTouchingWall: false, greenBalloonTouchingWall: false, wallVisible: true
Error: Assertion failed: induced charge did not change since last description, debugging info: forceMagnitude: 2.92421007109607, previousForceMagnitude: 2.92421007109607, greenBalloonVisible: false, yellowBalloonInducingCharge: true, greenBalloonInducingCharge: false, yellowBalloonTouchingWall: false, greenBalloonTouchingWall: false, wallVisible: true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/assert/js/assert.js:25:13)
at BalloonChargeDescriber.getInducedChargeChangeDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/balloons-and-static-electricity/js/balloons-and-static-electricity/view/describers/BalloonChargeDescriber.js:266:15)
at BalloonDescriber.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/balloons-and-static-electricity/js/balloons-and-static-electricity/view/describers/BalloonDescriber.js:867:48)
at BalloonNode.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BalloonNode.js:429:20)
at BASEView.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BASEView.js:172:28)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/joist/js/Sim.js:305:21
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/axon/js/Action.js:227:18)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/joist/js/Sim.js:1065:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/joist/js/Sim.js:1055:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/joist/js/Sim.js:1033:12)
id: Bayes Chrome
Snapshot from 4/29/2021, 12:45:55 AM

----------------------------------

balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1619678755408%22%2C%22timestamp%22%3A1619683290249%7D
Uncaught Error: Assertion failed: Tried to insert a disposed Node
Error: Assertion failed: Tried to insert a disposed Node
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/assert/js/assert.js:25:13)
at VBox.insertChild (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/scenery/js/nodes/Node.js:620:15)
at VBox.setChildren (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/scenery/js/nodes/Node.js:862:16)
at VBox.setChildren (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/scenery/js/nodes/LayoutBox.js:251:11)
at VBox.set children [as children] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/scenery/js/nodes/Node.js:892:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/scenery/js/nodes/Node.js:6701:23
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/sherpa/lib/lodash-4.17.4.js:9359:14)
at VBox.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/scenery/js/nodes/Node.js:6688:7)
at new LayoutBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/scenery/js/nodes/LayoutBox.js:106:10)
id: Bayes Chrome
Snapshot from 4/29/2021, 12:45:55 AM

----------------------------------

balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1619678755408%22%2C%22timestamp%22%3A1619693026436%7D
Uncaught Error: Assertion failed: Tried to insert a disposed Node
Error: Assertion failed: Tried to insert a disposed Node
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/assert/js/assert.js:25:13)
at VBox.insertChild (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/scenery/js/nodes/Node.js:620:15)
at VBox.setChildren (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/scenery/js/nodes/Node.js:862:16)
at VBox.setChildren (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/scenery/js/nodes/LayoutBox.js:251:11)
at VBox.set children [as children] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/scenery/js/nodes/Node.js:892:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/scenery/js/nodes/Node.js:6701:23
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/sherpa/lib/lodash-4.17.4.js:9359:14)
at VBox.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/scenery/js/nodes/Node.js:6688:7)
at new LayoutBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619678755408/scenery/js/nodes/LayoutBox.js:106:10)
id: Bayes Chrome
Snapshot from 4/29/2021, 12:45:55 AM
```

**Comment by jbphet** [comment]
I'm going to mark this as blocking publication, since we're getting close to re-publishing off of master.  If this problem is still happening we should resolve it and, if not, we should close the issue.  

I just checked CT and there is no sign of this occurring recently, and the history goes back to 10:56 pm yesterday, 7/25/2021.  I also ran multitouch fuzz for a bit and saw no problems.  Hopefully this has been fixed and there isn't anything to do other than to close it.

**Comment by samreid** [comment]
Should this be relabeled as blocks-sim-publication?

**Comment by jbphet** [comment]
Still not seeing this on CT.  I think it can be safely closed.

**Comment by jbphet** [comment]
Re-opening.  This occurred again on CT, late yesterday afternoon.  Here is the trace from CT:

```
balloons-and-static-electricity : pan-and-zoom-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627946219388/balloons-and-static-electricity/balloons-and-static-electricity_en.html?continuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22pan-and-zoom-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1627946219388%22%2C%22timestamp%22%3A1627986501202%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
Uncaught Error: Assertion failed: induced charge did not change since last description, debugging info: forceMagnitude: 2.140554518453034, previousForceMagnitude: 2.140554518453034, greenBalloonVisible: true, yellowBalloonInducingCharge: true, greenBalloonInducingCharge: false, yellowBalloonTouchingWall: false, greenBalloonTouchingWall: false, wallVisible: true
Error: Assertion failed: induced charge did not change since last description, debugging info: forceMagnitude: 2.140554518453034, previousForceMagnitude: 2.140554518453034, greenBalloonVisible: true, yellowBalloonInducingCharge: true, greenBalloonInducingCharge: false, yellowBalloonTouchingWall: false, greenBalloonTouchingWall: false, wallVisible: true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627946219388/assert/js/assert.js:25:13)
at BalloonChargeDescriber.getInducedChargeChangeDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627946219388/balloons-and-static-electricity/js/balloons-and-static-electricity/view/describers/BalloonChargeDescriber.js:266:15)
at BalloonDescriber.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627946219388/balloons-and-static-electricity/js/balloons-and-static-electricity/view/describers/BalloonDescriber.js:896:48)
at BalloonNode.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627946219388/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BalloonNode.js:446:20)
at BASEView.step (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627946219388/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BASEView.js:202:28)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627946219388/joist/js/Sim.js:332:21
at Action.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627946219388/axon/js/Action.js:227:18)
at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627946219388/joist/js/Sim.js:1083:31)
at Sim.stepOneFrame (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627946219388/joist/js/Sim.js:1073:12)
at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1627946219388/joist/js/Sim.js:1051:12)
id: Bayes Chrome
Snapshot from 8/2/2021, 5:16:59 PM
```

**Comment by jbphet** [comment]
I'm going to do some investigation on this since I know @jessegreenberg is working on other publication-blocking issues.

**Comment by jbphet** [comment]
I was able to duplicate this on my local machine by running fuzz testing, but it had to run for almost 10 minutes before the error was encountered.  The URL I used was:

```
http://localhost:8080/balloons-and-static-electricity/balloons-and-static-electricity_en.html?brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=true
```

The assertion message and stack trace matched the one in the comment above.

In essence, the assertion is the `BalloonChargeDescriber` saying, "Hey, you just told me to describe the changes to the charges in the wall, but as far as I can tell, there _were_ no changes to the charges in the wall."

Based on what I'm seeing the code and in the sim's state when this error is encountered, my current theory is that this is just a one-in-a-million sort of case where the balloon is dragged in a particular way that _usually_ causes the induced charges in the wall to change, but doesn't after this particular drag.

@jessegreenberg - It strikes me as a bit odd that the `getInducedChargeChangeDescription` method asserts in this case.  It doesn't say anything in the documentation about not calling it if the charges haven't changed, so how would clients even know not to do this?  I have two mutually exclusive thoughts on how this could be remedied.

1. Change `getInducedChargeChangeDescription` to say something like "No changes have occurred to the wall charges" in this case.  It will be extremely rare based on this testing, and it seems like a reasonable thing to say.
2. Add a method with a number something like `haveInducedChangesChanged` to `BalloonChangeDescriber` and use it to guard against calling `getInducedChargeChangeDescription` when no changes have occurred.

Over the @jessegreenberg to decide on next steps.  I'm happy to implement them if needed, since I've gotten a bit familiar with the code now.

**Comment by jessegreenberg** [comment]
Thanks for going into this issue @jbphet, your summary makes a lot of sense. I think either option you proposed could work but I prefer option (1). There is already a function that generates a string like that and I used it in this case. I removed the assertion.

Would you like to review this change? Otherwise I believe this can be closed.

**Comment by jbphet** [comment]
The change looks good to me, and I did several minutes of fuzz testing without seeing the problem, so I'm going to close.
