### ISSUE TITLE
CT vibrationManager.debug is not a function

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balloons-and-static-electricity#464]
```
balloons-and-static-electricity : fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1585588677828/balloons-and-static-electricity/balloons-and-static-electricity_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: vibrationManager.debug is not a function
TypeError: vibrationManager.debug is not a function
    at VibrationController.initialize (https://bayes.colorado.edu/continuous-testing/snapshot-1585588677828/balloons-and-static-electricity/js/balloons-and-static-electricity/view/vibrationController.js:24:22)
    at new BASEView (https://bayes.colorado.edu/continuous-testing/snapshot-1585588677828/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BASEView.js:154:23)
    at Screen.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1585588677828/balloons-and-static-electricity/js/balloons-and-static-electricity-main.js?bust=1585590998460:50:16)
    at Screen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1585588677828/joist/js/Screen.js:265:23)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1585588677828/joist/js/Sim.js:791:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585588677828/joist/js/Sim.js:810:25
id: Bayes Chrome
Approximately 3/30/2020, 11:17:57 AM
balloons-and-static-electricity : fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1585588677828/balloons-and-static-electricity/balloons-and-static-electricity_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: vibrationManager.debug is not a function
TypeError: vibrationManager.debug is not a function
    at VibrationController.initialize (https://bayes.colorado.edu/continuous-testing/snapshot-1585588677828/balloons-and-static-electricity/js/balloons-and-static-electricity/view/vibrationController.js:24:22)
    at new BASEView (https://bayes.colorado.edu/continuous-testing/snapshot-1585588677828/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BASEView.js:154:23)
    at Screen.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/snapshot-1585588677828/balloons-and-static-electricity/js/balloons-and-static-electricity-main.js?bust=1585590998460:50:16)
    at Screen.initializeView (https://bayes.colorado.edu/continuous-testing/snapshot-1585588677828/joist/js/Screen.js:265:23)
    at Array.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1585588677828/joist/js/Sim.js:791:16)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1585588677828/joist/js/Sim.js:810:25
id: Bayes Chrome
Approximately 3/30/2020, 11:17:57 AM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe this has since been fixed.
