### ISSUE TITLE
CT this.callback is not a function

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balloons-and-static-electricity#465]
```
balloons-and-static-electricity : top-level-unit-tests : require.js
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587854501239/balloons-and-static-electricity/balloons-and-static-electricity-tests.html
10 out of 11 tests passed. 1 failed.
WallDescriber: global failure failed:
Uncaught TypeError: this.callback is not a function
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587854501239/joist/js/SimLauncher.js:85


id: Bayes Chrome

balloons-and-static-electricity : top-level-unit-tests : require.js?ea
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587854501239/balloons-and-static-electricity/balloons-and-static-electricity-tests.html?ea
10 out of 11 tests passed. 1 failed.
WallDescriber: global failure failed:
Uncaught TypeError: this.callback is not a function
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587854501239/joist/js/SimLauncher.js:85


id: Bayes Chrome

balloons-and-static-electricity : top-level-unit-tests : require.js?ea
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587854501239/balloons-and-static-electricity/balloons-and-static-electricity-tests.html?ea
9 out of 10 tests passed. 1 failed.
WallDescriber: WallDescriber tests failed:
Uncaught TypeError: this.callback is not a function
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587854501239/joist/js/SimLauncher.js:85


id: Bayes Chrome

balloons-and-static-electricity : top-level-unit-tests : require.js?ea
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587854501239/balloons-and-static-electricity/balloons-and-static-electricity-tests.html?ea
9 out of 11 tests passed. 2 failed.
WallDescriber: global failure failed:
Uncaught TypeError: this.callback is not a function
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587854501239/joist/js/SimLauncher.js:85

WallDescriber: WallDescriber tests failed:
Died on test #1     at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587854501239/balloons-and-static-electricity/js/balloons-and-static-electricity/view/describers/WallDescriberTests.js:34:7: Assertion failed: boolean expected
Error: Assertion failed: boolean expected
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587854501239/assert/js/assert.js:22:13)
    at supportsGestureDescription (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587854501239/scenery-phet/js/accessibility/GrabDragInteraction.js:59:13)
    at new GrabDragInteraction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587854501239/scenery-phet/js/accessibility/GrabDragInteraction.js:220:38)
    at new BalloonNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587854501239/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BalloonNode.js:245:31)
    at new BASEView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587854501239/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BASEView.js:83:28)
    at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1587854501239/balloons-and-static-electricity/js/balloons-and-static-electricity/view/describers/WallDescriberTests.js:38:16)


id: Bayes Chrome
```

**Comment by KatieWoe** [comment]
Sorry, just saw this was reported elsewhere
