### ISSUE TITLE
CT phet.joist.sim.runOnNextFrame is not a function

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balloons-and-static-electricity#468]
```
balloons-and-static-electricity : top-level-unit-tests : require.js?ea
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/balloons-and-static-electricity/balloons-and-static-electricity-tests.html?ea
8 out of 10 tests passed. 2 failed.
BASESummaryNode: Summary tests failed:
Died on test #1 at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BASESummaryNodeTests.js:34:7: phet.joist.sim.runOnNextFrame is not a function
TypeError: phet.joist.sim.runOnNextFrame is not a function
at Node.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/tandem/js/PhetioObject.js:550:77)
at Node.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/scenery/js/nodes/Node.js:5349:36)
at Node.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/tandem/js/PhetioObject.js:197:20)
at MinusChargeNode.rasterized (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/scenery/js/nodes/Node.js:4615:17)
at new MinusChargesCanvasNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/balloons-and-static-electricity/js/balloons-and-static-electricity/view/MinusChargesCanvasNode.js:51:42)
at new WallNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/balloons-and-static-electricity/js/balloons-and-static-electricity/view/WallNode.js:67:28)
at new BASEView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BASEView.js:57:20)
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BASESummaryNodeTests.js:39:16)

WallDescriber: WallDescriber tests failed:
Died on test #1 at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/balloons-and-static-electricity/js/balloons-and-static-electricity/view/describers/WallDescriberTests.js:34:7: phet.joist.sim.runOnNextFrame is not a function
TypeError: phet.joist.sim.runOnNextFrame is not a function
at Node.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/tandem/js/PhetioObject.js:550:77)
at Node.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/scenery/js/nodes/Node.js:5349:36)
at Node.PhetioObject.dispose (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/tandem/js/PhetioObject.js:197:20)
at MinusChargeNode.rasterized (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/scenery/js/nodes/Node.js:4615:17)
at new MinusChargesCanvasNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/balloons-and-static-electricity/js/balloons-and-static-electricity/view/MinusChargesCanvasNode.js:51:42)
at new WallNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/balloons-and-static-electricity/js/balloons-and-static-electricity/view/WallNode.js:67:28)
at new BASEView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BASEView.js:57:20)
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1588900082851/balloons-and-static-electricity/js/balloons-and-static-electricity/view/describers/WallDescriberTests.js:38:16)

id: Bayes Chrome
Snapshot from 5/7/2020, 7:08:02 PM
```

**Comment by jessegreenberg** [comment]
It seems like we need a different way to run these unit tests. We keep running into problems where things are assuming they are being run in the context of a Sim. The tests either need to use a Sim, or stop using view components that assume they are in a sim context.

**Comment by zepumph** [comment]
Oops wrong issue, please see 
https://github.com/phetsims/balloons-and-static-electricity/issues/454#issuecomment-625904617

https://github.com/phetsims/balloons-and-static-electricity/commit/1c6c0482cce4b4ef95083bfd6269405f880df3ed

Fixed in those. Over to @jessegreenberg to review and close.

**Comment by jessegreenberg** [comment]
I see, thanks @zepumph - I still wanted to try something else to fix the problem I mentioned in https://github.com/phetsims/balloons-and-static-electricity/issues/468#issuecomment-625887636. The QUnit tests now use an actual running balloons-and-static-electricity sim now in an iframe so that we can remove the stubs. Ill be watching CT to make sure this is working over there.

**Comment by samreid** [comment]
After the commit, it also works on my localhost.  We'll see what CT says.

**Comment by jessegreenberg** [comment]
Thanks!

**Comment by jessegreenberg** [comment]
BASE has been clear for several days, closing!
