### ISSUE TITLE
PressListener in TwoSceneSelectionNode requires a Tandem.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balloons-and-static-electricity#473]
@jessegreenberg the changes you made to `TwoSceneSelectionNode` for #471 are causing CT failures:

```js
balloons-and-static-electricity : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601070252262/balloons-and-static-electricity/balloons-and-static-electricity_en.html?continuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1601070252262%22%2C%22timestamp%22%3A1601071441649%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601070252262/assert/js/assert.js:22:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601070252262/tandem/js/PhetioObject.js:240:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601070252262/tandem/js/PhetioObject.js:189:10)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601070252262/axon/js/Action.js:92:5)
at new PressListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601070252262/scenery/js/listeners/PressListener.js:245:23)
at new TwoSceneSelectionNode (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601070252262/balloons-and-static-electricity/js/balloons-and-static-electricity/view/TwoSceneSelectionNode.js:242:29)
at new ControlPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601070252262/balloons-and-static-electricity/js/balloons-and-static-electricity/view/ControlPanel.js:198:33)
at new BASEView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601070252262/balloons-and-static-electricity/js/balloons-and-static-electricity/view/BASEView.js:88:24)
at Screen.backgroundColorProperty [as createView] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601070252262/balloons-and-static-electricity/js/balloons-and-static-electricity-main.js:50:16)
at Screen.initializeView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1601070252262/joist/js/Screen.js:296:23)
id: Bayes Chrome
Snapshot from 9/25/2020, 3:44:12 PM
```

You replaced HighlightListener with PressListener, which defaults to `Tandem.REQUIRED`.  So you need to provide the `tandem` option to PressListener's constructor on line 242:

```js
  const highlightListener = new PressListener();
```

**Comment by jessegreenberg** [comment]
Thank you, passed tandem in above commit. Studio is running and standalone is fuzzing.
