### ISSUE TITLE
CT tried to insert a disposed node

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balloons-and-static-electricity#500]
```
balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619406875511/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1619406875511%22%2C%22timestamp%22%3A1619425863367%7D
Uncaught Error: Assertion failed: Tried to insert a disposed Node
Error: Assertion failed: Tried to insert a disposed Node
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619406875511/assert/js/assert.js:25:13)
at VBox.insertChild (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619406875511/scenery/js/nodes/Node.js:620:15)
at VBox.setChildren (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619406875511/scenery/js/nodes/Node.js:862:16)
at VBox.setChildren (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619406875511/scenery/js/nodes/LayoutBox.js:251:11)
at VBox.set children [as children] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619406875511/scenery/js/nodes/Node.js:892:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619406875511/scenery/js/nodes/Node.js:6701:23
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619406875511/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619406875511/sherpa/lib/lodash-4.17.4.js:9359:14)
at VBox.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619406875511/scenery/js/nodes/Node.js:6688:7)
at new LayoutBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1619406875511/scenery/js/nodes/LayoutBox.js:106:10)
id: Bayes Chrome
Snapshot from 4/25/2021, 9:14:35 PM
```

**Comment by KatieWoe** [comment]
This looks like it might have stopped for a bit but is back
```
balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1621225698973%22%2C%22timestamp%22%3A1621227084684%7D
Uncaught Error: Assertion failed: Tried to insert a disposed Node
Error: Assertion failed: Tried to insert a disposed Node
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/assert/js/assert.js:25:13)
at VBox.insertChild (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/scenery/js/nodes/Node.js:620:15)
at VBox.setChildren (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/scenery/js/nodes/Node.js:862:16)
at VBox.setChildren (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/scenery/js/nodes/LayoutBox.js:251:11)
at VBox.set children [as children] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/scenery/js/nodes/Node.js:892:10)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/scenery/js/nodes/Node.js:6756:23
at arrayEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/sherpa/lib/lodash-4.17.4.js:537:11)
at Function.forEach (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/sherpa/lib/lodash-4.17.4.js:9359:14)
at VBox.mutate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/scenery/js/nodes/Node.js:6743:7)
at new LayoutBox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1621225698973/scenery/js/nodes/LayoutBox.js:106:10)
id: Bayes Chrome
Snapshot from 5/16/2021, 10:28:18 PM
```

**Comment by jessegreenberg** [comment]
I am not seeing this while fuzzing the BASE state wrapper directly, and I haven't seen this for several iterations on CT. This was pretty rare, so I am fully sure if it is gone. But I also know that work has been done recently on PhET-iO state, so maybe this has been resolved. Since I am not seeing it while testing state explicitly, I am going to close for now.
