### ISSUE TITLE
CT instance should be marked as phetioDynamicElement:true

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balloons-and-static-electricity#512]
```
balloons-and-static-electricity : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/balloons-and-static-electricity/balloons-and-static-electricity_en.html?continuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1625108768523%22%2C%22timestamp%22%3A1625110844759%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:true
Error: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/assert/js/assert.js:25:13)
at PhetioCapsule.assertDynamicPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioDynamicElementContainer.js:259:17)
at PhetioCapsule.createDynamicElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioDynamicElementContainer.js:245:20)
at PhetioCapsule.create (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioCapsule.js:106:25)
at PhetioCapsule.getElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioCapsule.js:69:12)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/joist/js/preferences/NavigationBarPreferencesButton.js:44:49)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/TinyEmitter.js:86:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Emitter.js:39:24
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Action.js:227:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Emitter.js:64:19)
id: Bayes Chrome
Snapshot from 6/30/2021, 9:06:08 PM

----------------------------------

balloons-and-static-electricity : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/balloons-and-static-electricity/balloons-and-static-electricity_en.html?continuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1625108768523%22%2C%22timestamp%22%3A1625123906107%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:true
Error: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/assert/js/assert.js:25:13)
at PhetioCapsule.assertDynamicPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioDynamicElementContainer.js:259:17)
at PhetioCapsule.createDynamicElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioDynamicElementContainer.js:245:20)
at PhetioCapsule.create (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioCapsule.js:106:25)
at PhetioCapsule.getElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioCapsule.js:69:12)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/joist/js/preferences/NavigationBarPreferencesButton.js:44:49)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/TinyEmitter.js:86:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Emitter.js:39:24
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Action.js:227:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Emitter.js:64:19)
id: Bayes Chrome
Snapshot from 6/30/2021, 9:06:08 PM

----------------------------------

balloons-and-static-electricity : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/phet-io-wrappers/mirror-inputs/?sim=balloons-and-static-electricity&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1625108768523%22%2C%22timestamp%22%3A1625109941952%7D
Uncaught Error: Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:true
Error: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/assert/js/assert.js:25:13)
at PhetioCapsule.assertDynamicPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioDynamicElementContainer.js:259:17)
at PhetioCapsule.createDynamicElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioDynamicElementContainer.js:245:20)
at PhetioCapsule.create (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioCapsule.js:106:25)
at PhetioCapsule.getElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioCapsule.js:69:12)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/joist/js/preferences/NavigationBarPreferencesButton.js:44:49)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/TinyEmitter.js:86:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Emitter.js:39:24
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Action.js:227:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Emitter.js:64:19)
id: Bayes Chrome
Snapshot from 6/30/2021, 9:06:08 PM

----------------------------------

balloons-and-static-electricity : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/phet-io-wrappers/mirror-inputs/?sim=balloons-and-static-electricity&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1625108768523%22%2C%22timestamp%22%3A1625124648790%7D
Uncaught Error: Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:true
Error: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/assert/js/assert.js:25:13)
at PhetioCapsule.assertDynamicPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioDynamicElementContainer.js:259:17)
at PhetioCapsule.createDynamicElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioDynamicElementContainer.js:245:20)
at PhetioCapsule.create (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioCapsule.js:106:25)
at PhetioCapsule.getElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioCapsule.js:69:12)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/joist/js/preferences/NavigationBarPreferencesButton.js:44:49)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/TinyEmitter.js:86:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Emitter.js:39:24
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Action.js:227:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Emitter.js:64:19)
id: Bayes Chrome
Snapshot from 6/30/2021, 9:06:08 PM

----------------------------------

balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1625108768523%22%2C%22timestamp%22%3A1625109999875%7D
Uncaught Error: Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:true
Error: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/assert/js/assert.js:25:13)
at PhetioCapsule.assertDynamicPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioDynamicElementContainer.js:259:17)
at PhetioCapsule.createDynamicElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioDynamicElementContainer.js:245:20)
at PhetioCapsule.create (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioCapsule.js:106:25)
at PhetioCapsule.getElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioCapsule.js:69:12)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/joist/js/preferences/NavigationBarPreferencesButton.js:44:49)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/TinyEmitter.js:86:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Emitter.js:39:24
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Action.js:227:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Emitter.js:64:19)
id: Bayes Chrome
Snapshot from 6/30/2021, 9:06:08 PM

----------------------------------

balloons-and-static-electricity : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/studio/?sim=balloons-and-static-electricity&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1625108768523%22%2C%22timestamp%22%3A1625123663871%7D
Uncaught Error: Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:true
Error: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/assert/js/assert.js:25:13)
at PhetioCapsule.assertDynamicPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioDynamicElementContainer.js:259:17)
at PhetioCapsule.createDynamicElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioDynamicElementContainer.js:245:20)
at PhetioCapsule.create (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioCapsule.js:106:25)
at PhetioCapsule.getElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioCapsule.js:69:12)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/joist/js/preferences/NavigationBarPreferencesButton.js:44:49)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/TinyEmitter.js:86:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Emitter.js:39:24
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Action.js:227:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Emitter.js:64:19)
id: Bayes Chrome
Snapshot from 6/30/2021, 9:06:08 PM

----------------------------------

balloons-and-static-electricity : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/studio/?sim=balloons-and-static-electricity&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1625108768523%22%2C%22timestamp%22%3A1625152927064%7D
Uncaught Error: Uncaught Error: Assertion failed: instance should be marked as phetioDynamicElement:true
Error: Assertion failed: instance should be marked as phetioDynamicElement:true
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/assert/js/assert.js:25:13)
at PhetioCapsule.assertDynamicPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioDynamicElementContainer.js:259:17)
at PhetioCapsule.createDynamicElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioDynamicElementContainer.js:245:20)
at PhetioCapsule.create (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioCapsule.js:106:25)
at PhetioCapsule.getElement (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/tandem/js/PhetioCapsule.js:69:12)
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/joist/js/preferences/NavigationBarPreferencesButton.js:44:49)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/TinyEmitter.js:86:9)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Emitter.js:39:24
at Emitter.execute (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Action.js:227:18)
at Emitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625108768523/axon/js/Emitter.js:64:19)
id: Bayes Chrome
Snapshot from 6/30/2021, 9:06:08 PM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, this has been fixed.
