### ISSUE TITLE
CT A reference to the Pointer means it should have the pointerListener

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balloons-and-static-electricity#562]
```
balloons-and-static-electricity : interactive-description-fuzz-fuzzBoard-combo : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650459642668/balloons-and-static-electricity/balloons-and-static-electricity_en.html?continuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22interactive-description-fuzz-fuzzBoard-combo%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650459642668%22%2C%22timestamp%22%3A1650461428881%7D&brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Query: brand=phet&ea&supportsInteractiveDescription=true&fuzz&fuzzBoard&memoryLimit=1000
Uncaught Error: Assertion failed: A reference to the Pointer means it should have the pointerListener
Error: Assertion failed: A reference to the Pointer means it should have the pointerListener
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650459642668/assert/js/assert.js:25:13)
at assert (KeyboardDragListener.ts:886:16)
at interrupt (GrabDragInteraction.js:678:74)
at Array.forEach
at forEach (GrabDragInteraction.js:678:22)
at baseInteractionUpdate (GrabDragInteraction.js:637:9)
at turnToGrabbable (GrabDragInteraction.js:603:9)
at releaseDraggable (GrabDragInteraction.js:497:23)
at inputEvent (Input.ts:1818:91)
at dispatchToListeners (Input.ts:1856:11)
id: Bayes Chrome
Snapshot from 4/20/2022, 7:00:42 AM

----------------------------------

balloons-and-static-electricity : interactive-description-fuzzBoard : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1650459642668/balloons-and-static-electricity/balloons-and-static-electricity_en.html?continuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22interactive-description-fuzzBoard%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1650459642668%22%2C%22timestamp%22%3A1650461667943%7D&brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsInteractiveDescription=true&memoryLimit=1000
Unloaded frame before complete, window.location probably changed
id: Bayes Chrome
Snapshot from 4/20/2022, 7:00:42 AM
```

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, this one should be fixed via https://github.com/phetsims/scenery/issues/1408. I am not seeing this in the latest CT column  so I think that confirms this is fixed this morning.
