### ISSUE TITLE
CT PhET-iO API error:

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balloons-and-static-electricity#563]
```
balloons-and-static-electricity : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653482402514/studio/?sim=balloons-and-static-electricity&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1653482402514%22%2C%22timestamp%22%3A1653490043209%7D
Uncaught Error: Uncaught Error: Assertion failed: PhET-iO API error:
balloonsAndStaticElectricity.general.view.navigationBar.keyboardHelpButton.keyboardHelpDialogCapsule.keyboardHelpDialog.closeButton.enabledProperty: 1. After startup, only dynamic instances prescribed by the baseline file can be registered.
Error: Assertion failed: PhET-iO API error:
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1653482402514/assert/js/assert.js:28:13)
at assert (phetioAPIValidation.js:228:14)
at assertAPIError (phetioAPIValidation.js:141:15)
at listener (Timer.ts:33:10)
at (TinyEmitter.ts:107:42)
at emit (Sim.ts:964:24)
id: Bayes Chrome
Snapshot from 5/25/2022, 6:40:02 AM
```

**Comment by zepumph** [comment]
Tracked and fixed in https://github.com/phetsims/sun/issues/761, closing.
