### ISSUE TITLE
CT cannot set state while setting state

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/balloons-and-static-electricity#564]
```
balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654300717064%7D
Uncaught Error: Uncaught Error: Assertion failed: cannot set state while setting state
Error: Assertion failed: cannot set state while setting state
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (PhetioStateEngine.js:224:14)
at setState (PhetioStateEngine.js:263:9)
at setFullState (phetioEngine.js:1105:31)
at apply (phetioCommandProcessor.js:304:50)
at processCommand (phetioCommandProcessor.js:179:35)
at getReturn (phetioCommandProcessor.js:183:15)
at Array.map
at map (phetioCommandProcessor.js:177:29)
at processCommands (phetioCommandProcessor.js:113:15)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654310565285%7D
Uncaught Error: Uncaught Error: Assertion failed: cannot set state while setting state
Error: Assertion failed: cannot set state while setting state
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (PhetioStateEngine.js:224:14)
at setState (PhetioStateEngine.js:263:9)
at setFullState (phetioEngine.js:1105:31)
at apply (phetioCommandProcessor.js:304:50)
at processCommand (phetioCommandProcessor.js:179:35)
at getReturn (phetioCommandProcessor.js:183:15)
at Array.map
at map (phetioCommandProcessor.js:177:29)
at processCommands (phetioCommandProcessor.js:113:15)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654325972783%7D
Uncaught Error: Uncaught Error: Assertion failed: cannot set state while setting state
Error: Assertion failed: cannot set state while setting state
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (PhetioStateEngine.js:224:14)
at setState (PhetioStateEngine.js:263:9)
at setFullState (phetioEngine.js:1105:31)
at apply (phetioCommandProcessor.js:304:50)
at processCommand (phetioCommandProcessor.js:179:35)
at getReturn (phetioCommandProcessor.js:183:15)
at Array.map
at map (phetioCommandProcessor.js:177:29)
at processCommands (phetioCommandProcessor.js:113:15)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654341106485%7D
Uncaught Error: Uncaught Error: Assertion failed: cannot set state while setting state
Error: Assertion failed: cannot set state while setting state
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (PhetioStateEngine.js:224:14)
at setState (PhetioStateEngine.js:263:9)
at setFullState (phetioEngine.js:1105:31)
at apply (phetioCommandProcessor.js:304:50)
at processCommand (phetioCommandProcessor.js:179:35)
at getReturn (phetioCommandProcessor.js:183:15)
at Array.map
at map (phetioCommandProcessor.js:177:29)
at processCommands (phetioCommandProcessor.js:113:15)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654355841716%7D
Uncaught Error: Uncaught Error: Assertion failed: cannot set state while setting state
Error: Assertion failed: cannot set state while setting state
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (PhetioStateEngine.js:224:14)
at setState (PhetioStateEngine.js:263:9)
at setFullState (phetioEngine.js:1105:31)
at apply (phetioCommandProcessor.js:304:50)
at processCommand (phetioCommandProcessor.js:179:35)
at getReturn (phetioCommandProcessor.js:183:15)
at Array.map
at map (phetioCommandProcessor.js:177:29)
at processCommands (phetioCommandProcessor.js:113:15)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654369295845%7D
Uncaught Error: Uncaught Error: Assertion failed: cannot set state while setting state
Error: Assertion failed: cannot set state while setting state
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (PhetioStateEngine.js:224:14)
at setState (PhetioStateEngine.js:263:9)
at setFullState (phetioEngine.js:1105:31)
at apply (phetioCommandProcessor.js:304:50)
at processCommand (phetioCommandProcessor.js:179:35)
at getReturn (phetioCommandProcessor.js:183:15)
at Array.map
at map (phetioCommandProcessor.js:177:29)
at processCommands (phetioCommandProcessor.js:113:15)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654399513489%7D
Uncaught Error: Uncaught Error: Assertion failed: cannot set state while setting state
Error: Assertion failed: cannot set state while setting state
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (PhetioStateEngine.js:224:14)
at setState (PhetioStateEngine.js:263:9)
at setFullState (phetioEngine.js:1105:31)
at apply (phetioCommandProcessor.js:304:50)
at processCommand (phetioCommandProcessor.js:179:35)
at getReturn (phetioCommandProcessor.js:183:15)
at Array.map
at map (phetioCommandProcessor.js:177:29)
at processCommands (phetioCommandProcessor.js:113:15)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654411775836%7D
Uncaught Error: Uncaught Error: Assertion failed: cannot set state while setting state
Error: Assertion failed: cannot set state while setting state
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (PhetioStateEngine.js:224:14)
at setState (PhetioStateEngine.js:263:9)
at setFullState (phetioEngine.js:1105:31)
at apply (phetioCommandProcessor.js:304:50)
at processCommand (phetioCommandProcessor.js:179:35)
at getReturn (phetioCommandProcessor.js:183:15)
at Array.map
at map (phetioCommandProcessor.js:177:29)
at processCommands (phetioCommandProcessor.js:113:15)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654430174976%7D
Uncaught Error: Uncaught Error: Assertion failed: cannot set state while setting state
Error: Assertion failed: cannot set state while setting state
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (PhetioStateEngine.js:224:14)
at setState (PhetioStateEngine.js:263:9)
at setFullState (phetioEngine.js:1105:31)
at apply (phetioCommandProcessor.js:304:50)
at processCommand (phetioCommandProcessor.js:179:35)
at getReturn (phetioCommandProcessor.js:183:15)
at Array.map
at map (phetioCommandProcessor.js:177:29)
at processCommands (phetioCommandProcessor.js:113:15)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654458096717%7D
Uncaught Error: Uncaught Error: Assertion failed: alignBounds should be a non-empty finite Bounds2
Error: Assertion failed: alignBounds should be a non-empty finite Bounds2
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (AlignBox.ts:208:14)
at setAlignBounds (AlignBox.ts:227:50)
at (AlignGroup.ts:286:4)
at setBoxBounds (AlignGroup.ts:249:13)
at updateLayout (AlignGroup.ts:294:9)
at onAlignBoxResized (AlignBox.ts:191:18)
at listener (TinyEmitter.ts:94:8)
at emit (TinyStaticProperty.ts:58:9)
at notifyListeners (Node.ts:1481:30)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654493732779%7D
Uncaught Error: Uncaught Error: Assertion failed: cannot set state while setting state
Error: Assertion failed: cannot set state while setting state
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (PhetioStateEngine.js:224:14)
at setState (PhetioStateEngine.js:263:9)
at setFullState (phetioEngine.js:1105:31)
at apply (phetioCommandProcessor.js:304:50)
at processCommand (phetioCommandProcessor.js:179:35)
at getReturn (phetioCommandProcessor.js:183:15)
at Array.map
at map (phetioCommandProcessor.js:177:29)
at processCommands (phetioCommandProcessor.js:113:15)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654503773808%7D
Uncaught Error: Uncaught Error: Assertion failed: cannot set state while setting state
Error: Assertion failed: cannot set state while setting state
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (PhetioStateEngine.js:224:14)
at setState (PhetioStateEngine.js:263:9)
at setFullState (phetioEngine.js:1105:31)
at apply (phetioCommandProcessor.js:304:50)
at processCommand (phetioCommandProcessor.js:179:35)
at getReturn (phetioCommandProcessor.js:183:15)
at Array.map
at map (phetioCommandProcessor.js:177:29)
at processCommands (phetioCommandProcessor.js:113:15)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654516179177%7D
Uncaught Error: Uncaught Error: Assertion failed: cannot set state while setting state
Error: Assertion failed: cannot set state while setting state
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (PhetioStateEngine.js:224:14)
at setState (PhetioStateEngine.js:263:9)
at setFullState (phetioEngine.js:1105:31)
at apply (phetioCommandProcessor.js:304:50)
at processCommand (phetioCommandProcessor.js:179:35)
at getReturn (phetioCommandProcessor.js:183:15)
at Array.map
at map (phetioCommandProcessor.js:177:29)
at processCommands (phetioCommandProcessor.js:113:15)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM

----------------------------------

balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/phet-io-wrappers/state/?sim=balloons-and-static-electricity&phetioDebug=true&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1654295157038%22%2C%22timestamp%22%3A1654527123031%7D
Uncaught Error: Uncaught Error: Assertion failed: cannot set state while setting state
Error: Assertion failed: cannot set state while setting state
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1654295157038/assert/js/assert.js:28:13)
at assert (PhetioStateEngine.js:224:14)
at setState (PhetioStateEngine.js:263:9)
at setFullState (phetioEngine.js:1105:31)
at apply (phetioCommandProcessor.js:304:50)
at processCommand (phetioCommandProcessor.js:179:35)
at getReturn (phetioCommandProcessor.js:183:15)
at Array.map
at map (phetioCommandProcessor.js:177:29)
at processCommands (phetioCommandProcessor.js:113:15)
id: Bayes Puppeteer
Snapshot from 6/3/2022, 4:25:57 PM
```

**Comment by jessegreenberg** [comment]
Thanks, from that issue it seems that this is a more general issue so closing this one.
