### ISSUE TITLE
CT: TypeError in updateCheck.ts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/balloons-and-static-electricity#572]
Occurring on every cycle of CT:

```
balloons-and-static-electricity : fuzz : unbuilt
http://128.138.93.172/continuous-testing/ct-snapshots/1703255541257/balloons-and-static-electricity/balloons-and-static-electricity_en.html?continuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1703255541257%22%2C%22timestamp%22%3A1703255955872%7D&brand=phet&ea&fuzz
Query: brand=phet&ea&fuzz
Uncaught TypeError: Cannot read properties of undefined (reading 'chipper')
TypeError: Cannot read properties of undefined (reading 'chipper')
at chipper (updateCheck.ts:17:33)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1703255541257%2Fballoons-and-static-electricity%2Fballoons-and-static-electricity_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1703255541257%22%2C%22timestamp%22%3A1703255955872%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1703255541257%2Fballoons-and-static-electricity%2Fballoons-and-static-electricity_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz&duration=90000&testInfo=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1703255541257%22%2C%22timestamp%22%3A1703255955872%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1703255541257/balloons-and-static-electricity/balloons-and-static-electricity_en.html?continuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1703255541257%22%2C%22timestamp%22%3A1703255955872%7D&brand=phet&ea&fuzz
[CONSOLE] enabling assert
[PAGE ERROR] Error: TypeError: Cannot read properties of undefined (reading 'chipper')
at http://128.138.93.172/continuous-testing/ct-snapshots/1703255541257/chipper/dist/js/joist/js/updateCheck.js:16:34
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 12/22/2023, 7:32:21 AM
```

**Comment by jessegreenberg** [comment]
This one was was fixed in #571, closing.
