### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'getLength')

### ISSUE THREAD

**Issue by zepumph** [phetsims/balloons-and-static-electricity#575]
```
balloons-and-static-electricity : phet-io-state-fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1734695958590/phet-io-wrappers/state/?sim=balloons-and-static-electricity&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22balloons-and-static-electricity%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1734695958590%22%2C%22timestamp%22%3A1734699102976%7D
ERROR: Uncaught TypeError: Cannot read properties of undefined (reading 'getLength')
STACK: TypeError: Cannot read properties of undefined (reading 'getLength')
    at getLength (../../../../../../../balloons-and-static-electricity/js/balloons-and-static-electricity/model/BalloonModel.js:522:38)
    at getProgressThroughRegion (../../../../../../../../balloons-and-static-electricity/js/balloons-and-static-electricity/view/describers/BalloonPositionDescriber.js:480:50)
    at getKeyboardMovementAlert (../../../../../../../../balloons-and-static-electricity/js/balloons-and-static-electricity/view/describers/BalloonDescriber.js:865:47)
    at step (../../../../../../../balloons-and-static-electricity/js/balloons-and-static-electricity/view/BalloonNode.js:462:19)
    at step (../../../../../../../balloons-and-static-electricity/js/balloons-and-static-electricity/view/BASEView.js:216:26)
    at step (../../../../../joist/js/Sim.ts:472:18)
    at apply (../../../../../tandem/js/PhetioAction.ts:162:16)
    at execute (../../../../../joist/js/Sim.ts:1079:30)
    at stepSimulation (../../../../../joist/js/Sim.ts:1069:11)
    at stepOneFrame (../../../../../joist/js/Sim.ts:1044:11)

**Comment by zepumph** [comment]
It seems to be downstream from a PhET-iO state that likely didn't include the necessary items in state to get description working appropriately. For example, this makes an assumption that we are in fact moving, and so the range is undefined because there isn't a fallback case:

https://github.com/phetsims/balloons-and-static-electricity/blob/3cce6ea5770a6d217546b61d123bc979246ac635/js/balloons-and-static-electricity/model/BalloonModel.js#L512-L519

I would like to see if we can just be graceful, but keep this issue open to solve more appropriately when we work on PhET-iO state in this sim again. I am trying to clean up CT right now.

**Comment by zepumph** [comment]
I just want to see if this clears up CT. I don't believe it is right for the problem (that said, I have no idea how best to handle the description when state setting.

**Comment by jessegreenberg** [comment]
This has been working for several years now, I am going to leave it as is and close. I left the comment pointing to this issue in case we need to look again.
